imports:
- path: subnetwork.jinja
- path: instance-template-group-zonal.jinja
- path: instance-template-group-regional.jinja
- path: global-load-balancer.jinja
- path: internal-load-balancer.jinja
- path: scripts/web-startup-script.sh
  name: web-startup-script.sh
- path: scripts/db-startup-script.sh
  name: db-startup-script.sh


resources:

######################################################
## NETWORK and SUBNETS
######################################################

- name: test-network
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: false
    region: us-east1

- name: app-subnet
  type: subnetwork.jinja
  properties:
    cidr: 10.155.192.0/19
    subnet_name: public-subnet
    region: us-east1

- name: web-subnet
  type: subnetwork.jinja
  properties:
    cidr: 10.155.0.0/18
    subnet_name: app-web-subnet
    region: us-east1

- name: db-subnet
  type: subnetwork.jinja
  properties:
    cidr: 10.155.128.0/19
    subnet_name: db-subnet
    region: us-east1



######################################################
## FIREWALL RULES
######################################################

# Allow HTTP and HTTPS from any source
- name: fw-allow-http-https
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    targetTags:
    - http-server
    - https-server
    allowed:
    - IPProtocol: TCP
      ports: ["80","443"]

# Allow ICMP and SSH from any source
- name: fw-allow-icmp-ssh
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    allowed:
    - IPProtocol: TCP
      ports: ["22"]
    - IPProtocol: ICMP

# Allow any traffic from the app-web tier
- name: fw-allow-app-tier
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: [$(ref.app-subnet.ipCidrRange)]
    allowed:
    - IPProtocol: TCP
      ports: ["0-65535"]
    - IPProtocol: UDP
      ports: ["0-65535"]
    - IPProtocol: ICMP

# Allow any traffic from the web tier
- name: fw-allow-web-tier
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: [$(ref.web-subnet.ipCidrRange)]
    allowed:
    - IPProtocol: TCP
      ports: ["0-65535"]
    - IPProtocol: UDP
      ports: ["0-65535"]
    - IPProtocol: ICMP

# Allow any traffic from the DB tier
- name: fw-allow-db-tier
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: [$(ref.db-subnet.ipCidrRange)]
    allowed:
    - IPProtocol: TCP
      ports: ["0-65535"]
    - IPProtocol: UDP
      ports: ["0-65535"]
    - IPProtocol: ICMP

# Allow health checks from 130.211.0.0/22 and 35.191.0.0/16
# for internal load balancers
- name: fw-allow-tcp-healthcheck
  type: compute.v1.firewall
  properties:
    network: $(ref.test-network.selfLink)
    sourceRanges: ["130.211.0.0/22", "35.191.0.0/16"]
    allowed:
    - IPProtocol: TCP
      ports: ["0-65535"]



######################################################
## INSTANCE GROUPS
######################################################

## Create Web service tier
- name: web-green
  type: instance-template-group-regional.jinja
  properties:
    subnetwork: web-subnet
    region: us-east1
    tag: http-server
    minSize: 1
    maxSize: 2
    externalIP: true
    # 'color' is used as a metadata attribute to color some text on the web page
    # removed the entry if you don't need it
    color: green
    startup-script: web-startup-script.sh

- name: web-blue
  type: instance-template-group-regional.jinja
  properties:
    subnetwork: web-subnet
    region: us-east1
    tag: http-server
    minSize: 1
    maxSize: 2
    externalIP: true
    # 'color' is used as a metadata attribute to color some text on the web page
    # removed the entry if you don't need it
    color: blue
    startup-script: web-startup-script.sh

## Create App service tier
- name: app-green
  type: instance-template-group-zonal.jinja
  properties:
    subnetwork: app-subnet
    zones:
    - us-east1-b
    - us-east1-d
    tag: app-server
    minSize: 1
    maxSize: 2
    externalIP: true
    startup-script: web-startup-script.sh

- name: app-blue
  type: instance-template-group-zonal.jinja
  properties:
    subnetwork: app-subnet
    zones:
    - us-east1-b
    - us-east1-d
    tag: app-server
    minSize: 1
    maxSize: 2
    externalIP: true
    startup-script: web-startup-script.sh

## Create DB service tier
- name: db-green
  type: instance-template-group-zonal.jinja
  properties:
    subnetwork: db-subnet
    zones:
    - us-east1-b
    - us-east1-d
    tag: db-server
    minSize: 1
    maxSize: 2
    externalIP: true
    startup-script: db-startup-script.sh

- name: db-blue
  type: instance-template-group-zonal.jinja
  properties:
    subnetwork: db-subnet
    zones:
    - us-east1-b
    - us-east1-d
    tag: db-server
    minSize: 1
    maxSize: 2
    externalIP: true
    startup-script: db-startup-script.sh


######################################################
## LOAD BALANCERS
######################################################

## Reserve Global IP for Front Load Balancer
- name: lb-global-address
  type: compute.v1.globalAddresses


# - name: web-green-lb
#   type: external-load-balancer.jinja
#   properties:
#     port: 80
#     service-name: web-green
#     zones:
#     - us-east1-b
#     - us-east1-d
#
# - name: web-blue-lb
#   type: external-load-balancer.jinja
#   properties:
#     port: 80
#     service-name: web-blue
#     zones:
#     - us-east1-b
#     - us-east1-d

- name: app-green-lb
  type: internal-load-balancer.jinja
  properties:
    port: 80
    service-name: app-green
    zones:
    - us-east1-b
    - us-east1-d
    subnet: app-subnet

- name: app-blue-lb
  type: internal-load-balancer.jinja
  properties:
    port: 80
    service-name: app-blue
    zones:
    - us-east1-b
    - us-east1-d
    subnet: app-subnet

- name: db-green-lb
  type: internal-load-balancer.jinja
  properties:
    port: 80
    service-name: db-green
    zones:
    - us-east1-b
    - us-east1-d
    subnet: db-subnet

- name: db-blue-lb
  type: internal-load-balancer.jinja
  properties:
    port: 80
    service-name: db-blue
    zones:
    - us-east1-b
    - us-east1-d
    subnet: db-subnet
